function cfg = scenario_compute_constrained()
cfg = retina_nexus_sim_config(struct('scenario_name','COMPUTE_CONSTRAINED', ...
    'annual_patients',100000,'bandwidth_mbps',10,'peak_multiplier',1.0, ...
    'resources',struct('classifier_workers',1,'lesion_workers',1, ...
    'vessel_workers',1,'localization_workers',1,'xai_workers',1, ...
    'report_workers',1,'reviewers',1)));
end
