function cfg = scenario_review_scale()
cfg = retina_nexus_sim_config(struct('scenario_name','REVIEW_SCALE_UP', ...
    'annual_patients',100000,'bandwidth_mbps',10,'peak_multiplier',3.0, ...
    'resources',struct('reviewers',8)));
end
